UPDATE ENQUETESERVICE.ENQUETE_TYPE_LABEL SET ENQUETE_NAME = 'Korting IPA', U_TMS = CURRENT_TIMESTAMP WHERE ENQUETE_TYPE_ID = '0e7030ca-fac5-47c4-bfba-b0d5bd3afbf7' AND LANGUAGE = 'NL';
UPDATE ENQUETESERVICE.ENQUETE_TYPE_LABEL SET ENQUETE_NAME = 'Réduction AIP', U_TMS = CURRENT_TIMESTAMP WHERE ENQUETE_TYPE_ID = '0e7030ca-fac5-47c4-bfba-b0d5bd3afbf7' AND LANGUAGE = 'FR';

UPDATE ENQUETESERVICE.ENQUETE_TYPE_LABEL SET ENQUETE_NAME = 'Nacht-, ploegen- en volcontinuearbeid', U_TMS = CURRENT_TIMESTAMP WHERE ENQUETE_TYPE_ID = '3e3fc4fe-96d6-4b55-bec8-ce99dbe632ac' AND LANGUAGE = 'NL';
UPDATE ENQUETESERVICE.ENQUETE_TYPE_LABEL SET ENQUETE_NAME = 'Nachtarbeit, Schichtarbeit und durchgehende Schichtarbeit', U_TMS = CURRENT_TIMESTAMP WHERE ENQUETE_TYPE_ID = '3e3fc4fe-96d6-4b55-bec8-ce99dbe632ac' AND LANGUAGE = 'DE';
UPDATE ENQUETESERVICE.ENQUETE_TYPE_LABEL SET ENQUETE_NAME = 'Travail de nuit, travail en équipe et travail en continu', U_TMS = CURRENT_TIMESTAMP WHERE ENQUETE_TYPE_ID = '3e3fc4fe-96d6-4b55-bec8-ce99dbe632ac' AND LANGUAGE = 'FR';

UPDATE ENQUETESERVICE.ENQUETE_TYPE_LABEL SET ENQUETE_NAME = 'Startende ondernemingen', U_TMS = CURRENT_TIMESTAMP WHERE ENQUETE_TYPE_ID = '634d2252-a32a-4c10-9619-eebca4379550' AND LANGUAGE = 'NL';
UPDATE ENQUETESERVICE.ENQUETE_TYPE_LABEL SET ENQUETE_NAME = 'Entreprises débutantes', U_TMS = CURRENT_TIMESTAMP WHERE ENQUETE_TYPE_ID = '634d2252-a32a-4c10-9619-eebca4379550' AND LANGUAGE = 'FR';
UPDATE ENQUETESERVICE.ENQUETE_TYPE_LABEL SET ENQUETE_NAME = 'Anfänger-Unternehmen', U_TMS = CURRENT_TIMESTAMP WHERE ENQUETE_TYPE_ID = '634d2252-a32a-4c10-9619-eebca4379550' AND LANGUAGE = 'DE';