== Conventions

=== Application environment names

A typical enterprise Java application goes through a number of stages before it reaches production.
Each stage has a specific purpose and generally the stages are isolated from each other.
The next section describes the stages most commonly available:

. *Development (DEV)*: This is where you are making the next version of the application.
This is most likely on your local machine (unless you have a cloud programming environment)
. *Build (BUILD)*: Seperate environment for building your application e.g. Jenking or Bamboo
. *Test (TST)*: The Test environment is the first place where you and other people can see if all the code changes work together and no technical exceptions occur.
It gives you a first feeling of what production will behave or look like.
The basic functionalities will be tested here (by you or the test team). Early bugs will be spotted here.
This environment will resemble acceptance and production and it is the real test of how your coding changes will work in production.
. *Accept (ACC)*: The accept environment has to goal of validating if code changes are Ok to move to production.
Where in test you as a developer do the testing, in Accept someone e.g. business owner will perform and approve the changes.
. *Production (PRD)*: This is the only place where your application is used for real.

=== When should you write Javadoc?

[TIP]
=====
Try to choose method names that are readable and concise.
Keep method names as short as possible without loosing the method's responsibility.
=====

In real life it is time consuming to write a trivial JavaDoc for a method called _findEmployee_.
Any developer who reads the name of that method knows what it does.
It is also time consuming to correctly keep JavaDoc up to date.
If the _findEmployee_ method has an extra parameter, you have to update the JavaDoc.


Therefore the general guideline is *not* to write any JavaDoc unless

. You are writing a framework e.g. a query builder or task manager
. You need to clarify the way a method works and it cannot be derived solely from the method name

=== Naming conventions

==== Repository Vs Data Access Object (DAO)

Objects that access a data repository will be extended with _Repository_ instead of _DAO_.

==== Naming an implementation

Suppose we have an _EmployeeRepository_ interface.
If you write a Jdbc repository, you will name it _EmployeeJdbcRepository_

[TIP]
====
Sometimes there is only one available implementation you can think of at that moment.
This is the so called _Default_ implementation.
In this case you name it using the _Default_ keyword e.g. an _EmployeeService_ has the _EmployeeDefaultService_ implementation.
====

[NOTE]
====
Choosing a correct naming scheme for an implementation is alwasy tricky.
The following options were disregarded for a specific reason (in case we have an EmployeeRepository):

. *EmployeeRepositoryJpaImpl*: The _Impl_ keyword makes it unnecessary long.
. *JpaEmployeeRepository*: The _Jpa_ keyword belongs to the repository.
In this case it seems we are making a JpaEmployee.
====

=== Encoding

UTF-8 or higher (UTF-16) should be used as the base encoding. Stay away from windows (iso-...) or macOs encoding.




