== Introduction

The primary goal of this cookbook is to provide you, a developer,  with a *unified* way of building enterprise Java applications.
You will notice an increase in productivity and code quality when you follow the recipes in this cookbook.
If you work in a team, and each team member follows the rules in this cookbook, then you'll be able to understand eachothers code more quickly.

Since a book about coding standards is not very practical, all the guidelines you'll find are wrapped inside useful, day to day coding recipes e.g. _Write a repository_

=== Recipe's and flavours

[IMPORTANT]
====

If you are interested in learning how to use a specific technology, you should still use the technology's documentation.
In this cookbook you'll only find best practices and setup guides.

====


=== Technologies used in this book

[NOTE]
====

This cookbook focuses on how you should build a enterprise java applications and the guidelines you and your team should follow.
You won't learn how a technology works and what you can do with it.

====


Java offers a vast ecosystem of technologies you can use to build enterprise Java applications.
It is not possible to cover each and every technology in the cookbook.
The technologies currenly provided are:

. Build systems
.. https://gradle.org[Gradle^]
.. https://maven.apache.org[Maven^]
. Containers
.. http://projects.spring.io/spring-boot[Spring Boot^]
. Rest documenation
.. http://swagger.io[Swagger^]
. Database migration tools
.. http://www.liquibase.org[Liquibase^]
. Logging
.. http://logback.qos.ch/[Logback^]






