== Recipes for the persistence layer

=== Write a repository

.Repository method names
[TIP]
====

Use the naming conventions below when writing repository methods:

* *find(One)*: Use the _findByParameter_ syntax to name methods that will return one or more employees.
 E.g. an EmployeeRepository may have a _findByName_ and _findByNameAndAddress_ to retrieve employees
 based on the name or the combination of the employee name and its address.

* *find(and process result)*: In some case we do some processing or have some logic E.g. the EmployeeRepository has a find method that returns a map of the departments with
 the employees in that department. The return object is _Map<Department, List<Employee>>_.
 In this case we name the method _findAndGroupByDepartment_

* *count*: Count methods follow the same naming conventions as find methods.

* *update*: Use _updateByParameter_ methods for methods that change data in the repository. E.g. the EmployeeRepository
has the methods _updateByName_ and _updateByNameAndAddress_

* *delete*: Apply the _deleteByParameter_ naming convention. E.g. the EmployeeRepository has the _deleteByName_
and _deleteByNameAndAddress_ methods

* *insert*: Inserting new data into the repository will be done using the _insert_ method

====

==== Steps

. Choose a *name* for the repository e.g. the _EmployeeRepository_ will handle Employee persisted data
. Write the interface in the *repository package* e.g. _com.mycompany.module.repository_
. Write the *implementation* of the interface in the implementation package e.g. _com.mycompany.module.repository.impl_
.. Choose one of the *flavours* for implementing the repository e.g. a Spring JDBC repository
.. The *implementation* will be *named* using the chosen technology flavour and the _Impl suffix e.g. An Employee JDBC repository will be called _EmployeeRepositoryJDBCImpl_

==== Example

[source,java,indent=5]
----
public interface EmployeeRepository {

    Employee findOneById(Long id);

    Long countByDepartment(Department department);

    void update(Employee employee);

    void deleteById(Long id);

    Long insert(Employee employee);

}
----

An example repository inteface can be found here

==== Flavour: JDBC Repository With Spring

==== Flavour: Jpa Repsitory

=== Write a JDBC repository

=== Write a JPA repository

=== Write a service

=== Write a Rest controller